# fly.toml app configuration file generated for leaflet-citibike on 2023-06-07T17:24:27-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "Project-3--FOOTBALL-APP"
primary_region = "bos"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
